Vagrant.configure("2") do |config|

  config.vm.box = "bento/ubuntu-20.04"
  
  config.vm.synced_folder ".", "/vagrant", mount_options: ["dmode=775,fmode=600"]
  config.vm.define "ubuntu-dev" do |machine|
    machine.vm.network "private_network", ip: "192.168.99.91"
    machine.vm.hostname = 'zain'

	machine.vm.provider "virtualbox" do |vbox|
		vbox.memory = "2048"
		vbox.cpus = "1"
		vbox.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
		vbox.customize ["modifyvm", :id, "--natdnsproxy1", "on"]
        vbox.customize ["modifyvm", :id, "--name", "zain"]
        vbox.customize ["modifyvm", :id, "--natnet1", "192.168/16"]
	end
  end
end
 